#!/usr/bin/env python3
import argparse
import hashlib
import json
from pathlib import Path

import sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "tools/samer/classification-jobs-v1.json"
OUTPUT = ROOT / "public/data/simulatte-compact-classifiers.js"


def round_rows(rows):
    return [[round(float(value), 8) for value in row] for row in rows]


def round_values(values):
    return [round(float(value), 8) for value in values]


def label_description(label):
    return label.replace("-", " ")


def training_rows(labels):
    texts = []
    targets = []
    for label in labels:
        description = label_description(label)
        for template in (
            "{description}",
            "this request describes {description}",
            "the grounded visual class is {description}",
            "show {description}",
        ):
            texts.append(template.format(description=description))
            targets.append(label)
    return texts, targets


def model_row(model_id, model, score_kind):
    return {
        "id": model_id,
        "scoreKind": score_kind,
        "classes": [str(value) for value in model.classes_],
        "coefficients": round_rows(model.coef_),
        "intercepts": round_values(model.intercept_),
        "qualification": {
            "status": "evaluation-only-uncalibrated",
            "promotionEligible": False,
        },
    }


def build_head(job):
    labels = [label for label in job["labels"] if label not in job.get("scoredLabelsExclude", [])]
    texts, targets = training_rows(labels)
    vectorizer = TfidfVectorizer(
        lowercase=True,
        ngram_range=(1, 2),
        analyzer="word",
        sublinear_tf=True,
    )
    vectors = vectorizer.fit_transform(texts)
    linear_svc = LinearSVC(C=1.0, random_state=17).fit(vectors, targets)
    logistic = LogisticRegression(max_iter=400, random_state=17).fit(vectors, targets)
    vocabulary = sorted(vectorizer.vocabulary_.items(), key=lambda row: row[1])
    return {
        "id": job["id"],
        "inputUnit": job["inputUnit"],
        "labels": job["labels"],
        "scoredLabelsExclude": job.get("scoredLabelsExclude", []),
        "abstention": job["abstention"],
        "vectorizer": {
            "id": "simulatte.sklearn-tfidf-word-1-2.v1",
            "tokenPattern": "[a-z0-9]{2,}",
            "ngramRange": [1, 2],
            "sublinearTf": True,
            "norm": "l2",
            "vocabulary": [term for term, _index in vocabulary],
            "idf": round_values(vectorizer.idf_),
        },
        "models": {
            "linearSVC": model_row(
                "simulatte.browser-linear-svc-tfidf.v1",
                linear_svc,
                "decision-function",
            ),
            "logisticRegression": model_row(
                "simulatte.browser-logistic-tfidf.v1",
                logistic,
                "softmax-logit",
            ),
        },
    }


def build_artifact():
    source_bytes = SOURCE.read_bytes()
    source = json.loads(source_bytes)
    return {
        "schema": "simulatte.browserCompactClassifierArtifact.v1",
        "id": "simulatte-browser-compact-classifiers-v1",
        "source": {
            "path": "tools/samer/classification-jobs-v1.json",
            "sha256": hashlib.sha256(source_bytes).hexdigest(),
        },
        "generator": {
            "path": "tools/samer/build-browser-linear-classifiers.py",
            "sklearnVersion": sklearn.__version__,
        },
        "claimBoundary": "Browser-executable candidate weights trained from taxonomy descriptions. They are evaluation-only until candidate-specific calibration and a fresh sealed frontier qualify them.",
        "heads": [build_head(job) for job in source["jobs"]],
    }


def render(artifact):
    payload = json.dumps(artifact, separators=(",", ":"), ensure_ascii=True)
    return "\n".join((
        "// Generated by tools/samer/build-browser-linear-classifiers.py. Do not edit.",
        "(function attachSimulatteCompactClassifierArtifact(root, artifact) {",
        "  if (typeof module === 'object' && module.exports) module.exports = artifact;",
        "  root.SimulatteCompactClassifierArtifact = artifact;",
        f"}})(typeof globalThis !== 'undefined' ? globalThis : window, Object.freeze({payload}));",
        "",
    ))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render(build_artifact())
    if args.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != rendered:
            raise SystemExit("public/data/simulatte-compact-classifiers.js is stale")
        print("Browser linear classifier artifact is synchronized.")
        return
    OUTPUT.write_text(rendered)
    print("Wrote public/data/simulatte-compact-classifiers.js.")


if __name__ == "__main__":
    main()
